#!/usr/bin/env ruby -w -Ilib
require 'transloader'

def get_station_metadata(source, station, cache)
  case source
  when "environment_canada"
    provider = Transloader::EnvironmentCanadaProvider.new(cache)
    metadata = provider.load_station_metadata(station)
    provider.save_station_metadata(station, metadata)
  else
    puts "Support for source not implemented"
  end
end

# Parse Args
args = Transloader::Args.new(ARGV)

# Determine action

case args.verb
when :get
  case args.object
  when :metadata
    get_station_metadata(args.source, args.station, args.cache)
  when :observations
    puts "Not yet implemented"
  end
when :put
  case args.object
  when :metadata
    puts "Not yet implemented"
  when :observations
    puts "Not yet implemented"
  end
end
