#!/usr/bin/env ruby -Ilib
require 'transloader'

def get_metadata(options)
  case options.provider
  when "environment_canada"
    provider = Transloader::EnvironmentCanadaProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.save_metadata
  when "data_garrison"
    provider = Transloader::DataGarrisonProvider.new(options.cache)
    station = provider.get_station(user_id: options.user_id, 
                                   station_id: options.station_id)
    station.save_metadata
  when "campbell_scientific"
    provider = Transloader::CampbellScientificProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id, 
                                   data_urls: options.data_urls)
    station.save_metadata
  end
end

def put_metadata(options)
  case options.provider
  when "environment_canada"
    provider = Transloader::EnvironmentCanadaProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.upload_metadata(options.destination)
  when "data_garrison"
    provider = Transloader::DataGarrisonProvider.new(options.cache)
    station = provider.get_station(user_id: options.user_id,
                                   station_id: options.station_id)
    station.upload_metadata(options.destination)
  when "campbell_scientific"
    provider = Transloader::CampbellScientificProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.upload_metadata(options.destination)
  end
end

def get_observations(options)
  case options.provider
  when "environment_canada"
    provider = Transloader::EnvironmentCanadaProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.save_observations
  when "data_garrison"
    provider = Transloader::DataGarrisonProvider.new(options.cache)
    station = provider.get_station(user_id: options.user_id,
                                   station_id: options.station_id)
    station.save_observations
  when "campbell_scientific"
    provider = Transloader::CampbellScientificProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.save_observations
  end
end

def put_observations(options)
  case options.provider
  when "environment_canada"
    provider = Transloader::EnvironmentCanadaProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.save_metadata
    station.upload_metadata(options.destination)
    station.upload_observations_in_interval(options.destination, options.date)
  when "data_garrison"
    provider = Transloader::DataGarrisonProvider.new(options.cache)
    station = provider.get_station(user_id: options.user_id,
                                   station_id: options.station_id)
    station.upload_observations_in_interval(options.destination, options.date)
  when "campbell_scientific"
    provider = Transloader::CampbellScientificProvider.new(options.cache)
    station = provider.get_station(station_id: options.station_id)
    station.upload_observations_in_interval(options.destination, options.date)
  end
end

# Parse Args
parser = Transloader::CommandLineOptionParser.new
args = parser.parse(ARGV)

verb = args.verb
noun = args.noun

# Determine action
if verb == :get && noun == :metadata
  get_metadata(options)
elsif verb == :put && noun == :metadata
  put_metadata(options)
elsif verb == :get && noun == :observations
  get_observations(options)
elsif verb == :put && noun == :observations
  put_observations(options)
end
